# Site settings
title: Rúben Sousa
email: rubensousa.mieti@gmail.com
description: >
  I’m an Android developer currently freelancing.
  I spend a lot of my free time developing some projects in Android and Java, some of which are open source and available on my GitHub account:
#baseurl: "/"
url: "https://rubensousa.github.io"
fixedNav: 'true' # true or false
#theme: blue # green, blue, orange, purple, grey
twitterUsername: 
githubUsername: rubensousa
linkedinUsername: sousaruben
dribbbleUsername:
codepenUsername:
google_verify: m24iiMsYNx-eE86m8b4f7glua5ZstgwBUyMOw8Pt1Sc
# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
